### PR TITLE
Pass in webpack config file via command line parameter

### PR DESCRIPTION
**Pull request by lukastaegert**
In order to use different configurations within the same project, this pull request checks for the presence of a command line parameter and interprets this as the webpack.config file to use.

Possible use case: Run test-bed with different sub-sets of tests (unit and integration tests...) that also may require different configurations

This is a very simple implementation. Feel free to use a more involved implementation (using commander?) if you plan on adding other command line parameters in the future

By the way, great tool, it helps us a lot!

### CODE REVIEW

**Comment by lukastaegert** [comment]
Any comments about this one? Something like this would really help in our development.

**Comment by lukastaegert** [comment]
Any opinion on this one?

**Comment by dtinth** [comment]
Hello! I’m so sorry! I’ve been busy with other stuff that I don’t even notice the existence of this pull request. This proposal looks very nice.

However I think if this is going to be implemented, maybe an arguments parser, such as `yargs`, should be used. Then we can use the same command line syntax as `webpack`, e.g. `-c` for configuration file, or `-p` for port.

**Comment by lukastaegert** [comment]
Sounds good to me, this was also to find out how you feel about this and where you plan to go in the future. If I find the time, maybe I make another pull request. Thanks for the feedback!

**Pull request closed without merging**
